// flow-typed signature: 9d5dcfdfd1f0af1960f250ae08a82510
// flow-typed version: <<STUB>>/timm_v1.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'timm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timm/lib/timm_es6_flow' {
  declare module.exports: any;
}

declare module 'timm/lib/timm_es6' {
  declare module.exports: any;
}

declare module 'timm/lib/timm' {
  declare module.exports: any;
}

declare module 'timm/lib/timm.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timm/lib/timm_es6_flow.js' {
  declare module.exports: $Exports<'timm/lib/timm_es6_flow'>;
}
declare module 'timm/lib/timm_es6.js' {
  declare module.exports: $Exports<'timm/lib/timm_es6'>;
}
declare module 'timm/lib/timm.js' {
  declare module.exports: $Exports<'timm/lib/timm'>;
}
declare module 'timm/lib/timm.min.js' {
  declare module.exports: $Exports<'timm/lib/timm.min'>;
}
